/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    copy: typeof import('./components/global/PageHeading copy.vue')['default']
    GlobalBreadcrumbs: typeof import('./components/global/Breadcrumbs.vue')['default']
    GlobalButton: typeof import('./components/global/Button.vue')['default']
    GlobalDatePicker: typeof import('./components/global/DatePicker.vue')['default']
    GlobalLoader: typeof import('./components/global/Loader.vue')['default']
    GlobalNavBar: typeof import('./components/global/NavBar.vue')['default']
    GlobalPageContent: typeof import('./components/global/PageContent.vue')['default']
    GlobalPageFooter: typeof import('./components/global/PageFooter.vue')['default']
    GlobalPageHeader: typeof import('./components/global/PageHeader.vue')['default']
    GlobalPageHeading: typeof import('./components/global/PageHeading.vue')['default']
    GlobalSelect: typeof import('./components/global/Select.vue')['default']
    GlobalTable: typeof import('./components/global/Table.vue')['default']
    Loader: typeof import('./components/Loader.vue')['default']
    NavBar: typeof import('./components/NavBar.vue')['default']
    NavBarItem: typeof import('./components/NavBarItem.vue')['default']
    NavBarMenu: typeof import('./components/NavBarMenu.vue')['default']
    NavBarMobile: typeof import('./components/NavBarMobile.vue')['default']
    NavBarNavBar: typeof import('./components/NavBar/NavBar.vue')['default']
    NavBarNavBarItem: typeof import('./components/NavBar/NavBarItem.vue')['default']
    NavBarNavBarMenu: typeof import('./components/NavBar/NavBarMenu.vue')['default']
    NavBarNavBarMobile: typeof import('./components/NavBar/NavBarMobile.vue')['default']
    NavNavBar: typeof import('./components/nav/NavBar.vue')['default']
    NavNavBarItem: typeof import('./components/nav/NavBarItem.vue')['default']
    NavNavBarMenu: typeof import('./components/nav/NavBarMenu.vue')['default']
    NavNavBarMobile: typeof import('./components/nav/NavBarMobile.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
