/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Loader: typeof import('./components/Loader.vue')['default']
    NavBar: typeof import('./components/NavBar.vue')['default']
    NavBarItem: typeof import('./components/NavBarItem.vue')['default']
    NavBarMenu: typeof import('./components/NavBarMenu.vue')['default']
    NavBarMobile: typeof import('./components/NavBarMobile.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
